### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Suleman-Elahi** [ycui1984/DriveWorks#1]
If the code is open source, why are you asking for the subscription. Not against it, just want to know the catch.

Also, the logo image link is not working. It gives 404.

**Comment by ycui1984** [comment]
thanks @Suleman-Elahi for your question!
1. I am trying both, including open sourcing it plus publishing that as a ready to use service in the marketplace. 
2. I update the logo URL, turns out my method has a time out. I am thinking ways to serve the logo image permanently. But now that has been fixed temporarily.
